Algoritmo "crescente"

Var

   x, y : inteiro
   crescente, decrescente : caractere

Inicio

   escreval("Digite dois numeros: ")
   leia(x)
   leia(y)
   
   enquanto x <> y faca

      se x < y entao
         escreval("crescente")
      senao
         escreval("decrescente")
      fimse
      
      escreval("Digite outros dois numeros: ")
      leia(x)
      leia(y)


   fimenquanto
   
   

Fimalgoritmo